language: cpp
sudo: required

env:
  - secure: "y81XpWA0pgw18ZszT93q/1RRhsOdYfgVNAfntrNNQHxb4bFmUgxNdumxDWJrW3M4JvZLLlSQtaiszB1Q5gIHYd9dBXMmn9fs7r0X924ivLUt9gtRcPuYISBphYMda1mkZtum3BRSMPZthy7h9QCaIIZEoLzwBezg3XlKb+LaUfs="

before_install:
  -  APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/install-travis-env.sh -y && . ~/.profile && popd

script:
  - Tools/scripts/build_px4_v2_quad_travis.sh ${GITHUB_API_KEY}

before_deploy:
  - mkdir deploy_files
  - cp ArduCopter/ArduCopter-v2.px4 deploy_files
  - cp ../PX4Firmware/Build/px4fmu-v2_APM.build/firmware.elf deploy_files/fmu.elf
  - cp ../PX4Firmware/Build/px4io-v2_default.build/firmware.elf deploy_files/io.elf

deploy:
  provider: releases
  api-key: ${GITHUB_API_KEY}
  file:
  - "deploy_files/ArduCopter-v2.px4"
  - "deploy_files/fmu.elf"
  - "deploy_files/io.elf"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

notifications:
  slack: 3dr:DnBFaUDTVtQa5k18ODuAZRKL
